apiVersion: unfurl/v1.0.0
kind: Ensemble
metadata:
  uri: https://unfurl.cloud/user1/dashboard.git#:ensemble/ensemble.yaml
spec:
  service_template:
    # tosca service template goes here:
    topology_template:
      node_templates:
        aNodeTemplate:
          type: tosca:Root
status:
  # inputs:
  # outputs:
  instances:
    name: # root resource is always named "root"
      template: aNodeTemplate
      attributes:
        .interfaces:
          interfaceName: foo.bar.ClassName
      priority: required
      readyState:
        local: ok
        state: created
      lastConfigChange: A1312XNB0001
      lastStateChange: A1312XNB0001
      created: true
      instances:
        child1:
          template: aNodeTemplate
          # ...
lastJob:
  changeId: A0920aMf0000
  startTime: 2020-09-02-00-36-22-664763
  changelog: jobs/job2020-09-02-00-36-22-664763.yaml
  workflow: deploy
  options:
    force: true
  summary: 1 tasks (1 changed, 1 ok, 0 failed, 0 unknown, 0 skipped)
  startCommit: 628c2a4b633a26c1e8b1c116d3fdeef9bca89716
  specDigest: 037815dc8b56254219a96f359fd996c65e7d0754
  priority: required
  readyState:
    local: ok
jobLog: jobs.tsv
lock:
  runtime:
    unfurl:
      version: 1.1.0
      digest: 9c2c1b4a
    toolVersions: {}
  package_rules:
    - "unfurl.cloud/onecommons/* #main"
    - "unfurl.cloud/onecommons/std github.com/user1/myfork"
  repositories:
    - url: http://unfurl.cloud/onecommons/std
      package_id: unfurl.cloud/onecommons/std
      commit: 2da68fe0d1014805d15fc9134352626cb136e066
      initial: 2da68fe0d1014805d15fc9134352626cb136e066
      discovered_revision: 1.0.0
      tag: v1.0.0 # current commit is on this tag
