deployment_blueprints:
  production:
    cloud: unfurl.relationships.ConnectsTo.AWSAccount
    node_templates:
      host:
        type: HttpsProxyContainerComputeHost
        requirements:
        - host: host_host
        - dns: host_dns
      host_host:
        type: EC2Compute
        properties:
          num_cpus: 2
          mem_size:
            get_input: mem_size
          disk_size:
            get_input: disk_size
      host_dns:
          type: Route53DNSZone
          properties:
            name: example.com
      db:
        type: AwsRdsPostgres
  dev:
    cloud: unfurl.relationships.ConnectsTo.K8sCluster
    node_templates:
      host:
        type: PublicK8sContainerHost
        properties:
          labels:
            kompose.volume.size:
              get_input: disk_size
        requirements:
        - dns: unfurl.nodes.DNSZone
      db:
        type: PostgresDBInstance
        requirements:
        - host: db_host_requirement
        properties:
          database_name: my_db
      db_host_requirement:
        type: PrivateK8sContainerHost
imports:
- file: aws/db.yaml
  repository: std
- file: k8s.yaml
  repository: std
- file: aws/compute.yaml
  repository: std
- file: dns_services.yaml
  repository: std
