FROM python:3.13-slim

ENV UNFURL_HOME=""

RUN apt-get -qq update && \
    apt-get -qq --no-install-recommends install -y git curl unzip wget expect build-essential && \
    apt-get -qq clean -y && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --user-group unfurl

COPY . /unfurl

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    . "$HOME/.cargo/env" && \
    cargo install oas3-gen --version "$(cat /unfurl/rust/server/.oas3-gen-version)" --locked && \
    cargo build --release --manifest-path /unfurl/rust/Cargo.toml --package unfurl-server && \
    cp /unfurl/rust/target/release/unfurl-server /usr/local/bin/unfurl-server && \
    pip install --no-cache-dir /unfurl[server] && \
    rm -rf /unfurl ~/.cargo ~/.rustup

USER unfurl:unfurl

EXPOSE 5000

ARG NUM_WORKERS=4
ENV NUM_WORKERS=${NUM_WORKERS}
ENTRYPOINT gunicorn -b=0.0.0.0:5000 -w=${NUM_WORKERS} unfurl.server.serve:app
